### PR TITLE
feat: integrate starknetId

### PR DESCRIPTION
**Pull request by Marchand-Nicolas**
close: #217 
image
image

### CODE REVIEW

**Review by YohanTz — DISMISSED** [review]

**Comment by YohanTz** [comment]
Hey @Marchand-Nicolas, thanks for this PR :) I just tried the deployed version of your branch here: https://bridge-mainnet-g785qgwco-screenshotlabs.vercel.app/
I connected my argent wallet with a starknet id linked to it, but it is not showing in the connect wallet button, do you know why?

**Comment by Marchand-Nicolas** [comment]
> Hey @Marchand-Nicolas, thanks for this PR :) I just tried the deployed version of your branch here: https://bridge-mainnet-g785qgwco-screenshotlabs.vercel.app/ I connected my argent wallet with a starknet id linked to it, but it is not showing in the connect wallet button, do you know why?

I remember getting this kind of issue with jedi swap in my PR. Last time I just had to update starknet react, I'm going to try it

**Comment by YohanTz** [comment]
@Marchand-Nicolas I'm just pushing a commit to update the lock file

**Comment by YohanTz** [comment]
@Marchand-Nicolas C'est good pour le nom 👍🏽 Juste pour l'image de profil j'ai ca pour le moment, je crois pas que j'ai une image associée a mon profil:
Screenshot 2024-05-24 at 00 45 11

**Comment by Marchand-Nicolas** [comment]
> @Marchand-Nicolas It's good for the name, thanks 👍🏽 I have this for the profile picture though: Screenshot 2024-05-24 at 00 45 11
> 
> I don't think that I have an associated image to my address

When no image is associated, a default image is still returned. But it's weird, it looks like the Image component doesn't want to show it. I can try to switch to a simple

**Comment by Marchand-Nicolas** [comment]
Yes, we are getting 
image
(the image is a SVG)

**Comment by Marchand-Nicolas** [comment]
> Hey @Marchand-Nicolas, I Just tried and it is showing me a starknet ID image even when there is no starknet id associated to the current address: Screenshot 2024-05-24 at 20 09 54 (I have no Starknet ID associated to this address)

Yes, it's normal, it's the default PFP for any address, it's showing the same on starknet.quest for example
image
If you prefer I can disable it if no starknetId is linked ?

**Comment by YohanTz** [comment]
> > Hey @Marchand-Nicolas, I Just tried and it is showing me a starknet ID image even when there is no starknet id associated to the current address: Screenshot 2024-05-24 at 20 09 54 (I have no Starknet ID associated to this address)
> 
> Yes, it's normal, it's the default PFP for any address, it's showing the same on starknet.quest for example image If you prefer I can disable it if no starknetId is linked ?

Oh ok, I think it's better to disable it if no starknet id linked yes 👍🏽

**Comment by YohanTz** [comment]
All good, thanks for the PR @Marchand-Nicolas!

**Review by YohanTz — APPROVED** [review]

**Pull request merged**
